; ******************************************************************************************
; working environment for Trim_Indicator of custom firmware
; ******************************************************************************************
; Common build settings across this custom device
[env_Trim_Indicator]
build_flags =
	${env.build_flags}												; include standard build flags
	-DMF_CUSTOMDEVICE_SUPPORT=1										; Required for Custom Devices
	;-DMF_CUSTOMDEVICE_HAS_UPDATE									; if the custom device needs to be updated, uncomment this. W/o the following define it will be done each loop()
	;-DMF_CUSTOMDEVICE_POLL_MS=10 									; time in ms between updating custom device, uncomment this if custom device needs to be updated regulary
	;-DHAS_CONFIG_IN_FLASH											; undefine this and add your configuration to MFCustomDevicesConfig.h to save the config in Flash !!Core FW version must be at least 2.5.2!!
	-I./src/src/MF_CustomDevice										; don't change this one!
	-I./Trim_Indicator													; Include files for your custom device, replace "Trim_Indicator" by your folder name
    -DMF_SEGMENT_SUPPORT=0
    -DMF_LCD_SUPPORT=0
    -DMF_STEPPER_SUPPORT=0
    -DMF_SERVO_SUPPORT=0
    -DMF_ANALOG_SUPPORT=0
    -DMF_OUTPUT_SHIFTER_SUPPORT=0
    -DMF_INPUT_SHIFTER_SUPPORT=0
    -DMF_MUX_SUPPORT=0
    -DMF_DIGIN_MUX_SUPPORT=0
build_src_filter = 
	+<../Trim_Indicator>													; build files for your custom device, replace "Trim_Indicator" by your folder name
lib_deps =	fastled/FastLED@^3.7.5														; You can add additional libraries if required
custom_core_firmware_version = 2.5.1								; define the version from the core firmware files your build should base on
custom_device_folder = Trim_Indicator										; path to your Custom Device Sources, replace "Trim_Indicator" by your folder name
custom_community_project = Trim Indicator								; Should match "Project" from section "Community" within the board.json file, it's the name of the ZIP file

; Build settings for the Arduino Nano with Custom Firmware Trim_Indicator
[env:Trim_Indicator_nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = 
	${env_Trim_Indicator.build_flags}										; don't change this one!
	-I./src/_Boards/Atmel/Board_Nano								; Include the required board definition. If you need your own definition, adapt this to your path (e.g. -I./CustomDevices/_Trim_Indicator/_Boards)
	'-DMOBIFLIGHT_TYPE="Trim_Indicator_Nano"'					; this must match with "MobiFlightType" within the .json file
	'-DMOBIFLIGHT_NAME="Trim Indicator Nano"' 						; this will show up as Name in the settings dialog unless it gets change from there
build_src_filter = 
	${env.build_src_filter}											; don't change this one!
	${env_Trim_Indicator.build_src_filter}								; don't change this one!
lib_deps = 
	${env.lib_deps}													; don't change this one!
	${env.custom_lib_deps_Atmel}									; don't change this one!
	${env_Trim_Indicator.lib_deps}										; don't change this one!
monitor_speed = 115200												; don't change this one!
extra_scripts = 
	${env.extra_scripts}											; don't change this one!
custom_core_firmware_version = ${env_Trim_Indicator.custom_core_firmware_version}	; don't change this one!
custom_community_project = ${env_Trim_Indicator.custom_community_project}			; don't change this one!
custom_device_folder = ${env_Trim_Indicator.custom_device_folder}					; don't change this one!
